name: wtf_shared
description: Shared models, services, widgets, and utilities for the WTF Flutter assessment.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
